-ifndef(LABA_HRL).
-define(LABA_HRL, true).

-include("predef.hrl").

-define(TYPE_LABA,1).
-define(TYPE_SUPER_LABA,2).

-define(LABA_RATE_EST_MAPLIST, [?ETS_LABA_RATE_LIST_1, ?ETS_LABA_RATE_LIST_2, ?ETS_LABA_RATE_LIST_3,
    ?ETS_LABA_RATE_LIST_4, ?ETS_LABA_RATE_LIST_5, ?ETS_LABA_RATE_LIST_6, ?ETS_LABA_RATE_LIST_7,
    ?ETS_LABA_RATE_LIST_8, ?ETS_LABA_RATE_LIST_9, ?ETS_LABA_RATE_LIST_10, ?ETS_LABA_RATE_LIST_BLACK_ROOM]).

-define(LABA_TESTTYPE2_RATE_EST_MAPLIST, [?ETS_LABA_T2_RATE_LIST_1, ?ETS_LABA_T2_RATE_LIST_2, ?ETS_LABA_T2_RATE_LIST_3,
    ?ETS_LABA_T2_RATE_LIST_4, ?ETS_LABA_T2_RATE_LIST_5, ?ETS_LABA_T2_RATE_LIST_6, ?ETS_LABA_T2_RATE_LIST_7,
    ?ETS_LABA_T2_RATE_LIST_8, ?ETS_LABA_T2_RATE_LIST_9, ?ETS_LABA_T2_RATE_LIST_10]).

-define(SUPER_LABA_RATE_EST_MAPLIST, [?ETS_SUPER_LABA_RATE_LIST_1, ?ETS_SUPER_LABA_RATE_LIST_2, ?ETS_SUPER_LABA_RATE_LIST_3,
    ?ETS_SUPER_LABA_RATE_LIST_4, ?ETS_SUPER_LABA_RATE_LIST_5, ?ETS_SUPER_LABA_RATE_LIST_6, ?ETS_SUPER_LABA_RATE_LIST_7,
    ?ETS_SUPER_LABA_RATE_LIST_8, ?ETS_SUPER_LABA_RATE_LIST_9, ?ETS_SUPER_LABA_RATE_LIST_10]).

-define(SUPER_LABA_TESTTYPE2_RATE_EST_MAPLIST, [?ETS_SUPER_LABA_T2_RATE_LIST_1, ?ETS_SUPER_LABA_T2_RATE_LIST_2, ?ETS_SUPER_LABA_T2_RATE_LIST_3,
    ?ETS_SUPER_LABA_T2_RATE_LIST_4, ?ETS_SUPER_LABA_T2_RATE_LIST_5, ?ETS_SUPER_LABA_T2_RATE_LIST_6, ?ETS_SUPER_LABA_T2_RATE_LIST_7,
    ?ETS_SUPER_LABA_T2_RATE_LIST_8, ?ETS_SUPER_LABA_T2_RATE_LIST_9, ?ETS_SUPER_LABA_T2_RATE_LIST_10]).

-endif.
